import type { Stadium } from '@/types'

// Drop your images in src/assets/stadiums/ with these exact filenames
import metlife from '@/assets/stadiums/metlife.jpg'
import att from '@/assets/stadiums/att.jpg'
import sofi from '@/assets/stadiums/sofi.jpg'
import levis from '@/assets/stadiums/levis.jpg'
import hardRock from '@/assets/stadiums/hard-rock.jpg'
import arrowhead from '@/assets/stadiums/arrowhead.jpg'
import nrg from '@/assets/stadiums/nrg.jpg'
import lincoln from '@/assets/stadiums/lincoln.jpg'
import gillette from '@/assets/stadiums/gillette.jpg'
import lumen from '@/assets/stadiums/lumen.jpg'
import mercedesBenz from '@/assets/stadiums/mercedes-benz.jpg'
import bcPlace from '@/assets/stadiums/bc-place.jpg'
import bmo from '@/assets/stadiums/bmo.jpg'
import azteca from '@/assets/stadiums/azteca.jpg'
import akron from '@/assets/stadiums/akron.jpg'
import bbva from '@/assets/stadiums/bbva.jpg'

export const MOCK_STADIUMS: Stadium[] = [
  {
    id: '1',
    slug: 'metlife',
    name: 'MetLife Stadium',
    city: 'New York / New Jersey',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 82500,
    hero_image_url: metlife,
    note: 'Final venue · Largest capacity',
    avg_atmosphere: 4.6,
    avg_food: 4.2,
    avg_hotel: 4.3,
    avg_safety: 4.7,
    avg_rating: 4.6,
    total_reviews: 3241,
    transport_status: 'Active',
    security_score: 4.7,
    year_opened: 2010,
    surface: 'FieldTurf',
    roof_type: 'Open Air',
  },
  {
    id: '2',
    slug: 'att',
    name: 'AT&T Stadium',
    city: 'Dallas / Arlington',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 92967,
    hero_image_url: att,
    note: 'Jerry World · Retractable roof',
    avg_atmosphere: 4.5,
    avg_food: 4.4,
    avg_hotel: 4.4,
    avg_safety: 4.6,
    avg_rating: 4.5,
    total_reviews: 2890,
    transport_status: 'Active',
    security_score: 4.6,
    year_opened: 2009,
    surface: 'Natural Grass',
    roof_type: 'Retractable',
  },
  {
    id: '3',
    slug: 'sofi',
    name: 'SoFi Stadium',
    city: 'Los Angeles',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 70240,
    hero_image_url: sofi,
    note: 'Hollywood glam · Premier venue',
    avg_atmosphere: 4.7,
    avg_food: 4.6,
    avg_hotel: 4.5,
    avg_safety: 4.5,
    avg_rating: 4.7,
    total_reviews: 3102,
    transport_status: 'Active',
    security_score: 4.5,
    year_opened: 2020,
    surface: 'Natural Grass',
    roof_type: 'Fixed Roof',
  },
  {
    id: '4',
    slug: 'levis',
    name: "Levi's Stadium",
    city: 'San Francisco Bay Area',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 70909,
    hero_image_url: levis,
    note: 'Silicon Valley tech hub',
    avg_atmosphere: 4.3,
    avg_food: 4.5,
    avg_hotel: 4.3,
    avg_safety: 4.6,
    avg_rating: 4.4,
    total_reviews: 2134,
    transport_status: 'Active',
    security_score: 4.6,
    year_opened: 2014,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '5',
    slug: 'hard-rock',
    name: 'Hard Rock Stadium',
    city: 'Miami',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 67518,
    hero_image_url: hardRock,
    note: '3rd-place match · South Beach vibes',
    avg_atmosphere: 4.5,
    avg_food: 4.4,
    avg_hotel: 4.4,
    avg_safety: 4.5,
    avg_rating: 4.5,
    total_reviews: 2012,
    transport_status: 'Active',
    security_score: 4.5,
    year_opened: 1987,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '6',
    slug: 'arrowhead',
    name: 'Arrowhead Stadium',
    city: 'Kansas City',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 76640,
    hero_image_url: arrowhead,
    note: 'Loudest NFL stadium',
    avg_atmosphere: 4.9,
    avg_food: 4.3,
    avg_hotel: 4.2,
    avg_safety: 4.6,
    avg_rating: 4.6,
    total_reviews: 2245,
    transport_status: 'Active',
    security_score: 4.6,
    year_opened: 1972,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '7',
    slug: 'nrg',
    name: 'NRG Stadium',
    city: 'Houston',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 72220,
    hero_image_url: nrg,
    note: 'Air-conditioned · Retractable roof',
    avg_atmosphere: 4.4,
    avg_food: 4.5,
    avg_hotel: 4.3,
    avg_safety: 4.4,
    avg_rating: 4.4,
    total_reviews: 1998,
    transport_status: 'Active',
    security_score: 4.4,
    year_opened: 2002,
    surface: 'Natural Grass',
    roof_type: 'Retractable',
  },
  {
    id: '8',
    slug: 'lincoln',
    name: 'Lincoln Financial Field',
    city: 'Philadelphia',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 69328,
    hero_image_url: lincoln,
    note: 'City of Brotherly Love',
    avg_atmosphere: 4.7,
    avg_food: 4.1,
    avg_hotel: 4.2,
    avg_safety: 4.3,
    avg_rating: 4.4,
    total_reviews: 2011,
    transport_status: 'Active',
    security_score: 4.3,
    year_opened: 2003,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '9',
    slug: 'gillette',
    name: 'Gillette Stadium',
    city: 'Boston',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 65878,
    hero_image_url: gillette,
    note: 'Patriots home · New England',
    avg_atmosphere: 4.5,
    avg_food: 4.2,
    avg_hotel: 4.3,
    avg_safety: 4.6,
    avg_rating: 4.4,
    total_reviews: 1703,
    transport_status: 'Active',
    security_score: 4.6,
    year_opened: 2002,
    surface: 'FieldTurf',
    roof_type: 'Open Air',
  },
  {
    id: '10',
    slug: 'lumen',
    name: 'Lumen Field',
    city: 'Seattle',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 69000,
    hero_image_url: lumen,
    note: '12th Man atmosphere',
    avg_atmosphere: 4.6,
    avg_food: 4.5,
    avg_hotel: 4.4,
    avg_safety: 4.6,
    avg_rating: 4.5,
    total_reviews: 2087,
    transport_status: 'Active',
    security_score: 4.6,
    year_opened: 2002,
    surface: 'FieldTurf',
    roof_type: 'Open Air',
  },
  {
    id: '11',
    slug: 'mercedes-benz',
    name: 'Mercedes-Benz Stadium',
    city: 'Atlanta',
    country: 'USA',
    flag: '🇺🇸',
    capacity: 75000,
    hero_image_url: mercedesBenz,
    note: 'Falcon wing roof · Semifinal venue',
    avg_atmosphere: 4.7,
    avg_food: 4.6,
    avg_hotel: 4.5,
    avg_safety: 4.6,
    avg_rating: 4.6,
    total_reviews: 2341,
    transport_status: 'Active',
    security_score: 4.6,
    year_opened: 2017,
    surface: 'Natural Grass',
    roof_type: 'Retractable',
  },
  {
    id: '12',
    slug: 'bc-place',
    name: 'BC Place',
    city: 'Vancouver',
    country: 'Canada',
    flag: '🇨🇦',
    capacity: 54500,
    hero_image_url: bcPlace,
    note: 'Mountains & ocean views',
    avg_atmosphere: 4.4,
    avg_food: 4.6,
    avg_hotel: 4.5,
    avg_safety: 4.8,
    avg_rating: 4.5,
    total_reviews: 1654,
    transport_status: 'Active',
    security_score: 4.8,
    year_opened: 1983,
    surface: 'FieldTurf',
    roof_type: 'Retractable',
  },
  {
    id: '13',
    slug: 'bmo',
    name: 'BMO Field',
    city: 'Toronto',
    country: 'Canada',
    flag: '🇨🇦',
    capacity: 45736,
    hero_image_url: bmo,
    note: "Canada's soccer capital",
    avg_atmosphere: 4.3,
    avg_food: 4.5,
    avg_hotel: 4.4,
    avg_safety: 4.7,
    avg_rating: 4.4,
    total_reviews: 1432,
    transport_status: 'Active',
    security_score: 4.7,
    year_opened: 2007,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '14',
    slug: 'azteca',
    name: 'Estadio Azteca',
    city: 'Mexico City',
    country: 'Mexico',
    flag: '🇲🇽',
    capacity: 87523,
    hero_image_url: azteca,
    note: 'Temple of football · Opening match',
    avg_atmosphere: 5.0,
    avg_food: 4.4,
    avg_hotel: 4.2,
    avg_safety: 4.1,
    avg_rating: 4.7,
    total_reviews: 4521,
    transport_status: 'Active',
    security_score: 4.1,
    year_opened: 1966,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '15',
    slug: 'akron',
    name: 'Estadio AKRON',
    city: 'Guadalajara',
    country: 'Mexico',
    flag: '🇲🇽',
    capacity: 48071,
    hero_image_url: akron,
    note: 'Chivas home · Cultural hub',
    avg_atmosphere: 4.7,
    avg_food: 4.3,
    avg_hotel: 4.2,
    avg_safety: 4.2,
    avg_rating: 4.5,
    total_reviews: 2103,
    transport_status: 'Active',
    security_score: 4.2,
    year_opened: 2010,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
  {
    id: '16',
    slug: 'bbva',
    name: 'Estadio BBVA',
    city: 'Monterrey',
    country: 'Mexico',
    flag: '🇲🇽',
    capacity: 53460,
    hero_image_url: bbva,
    note: 'Mountain backdrop · Electric',
    avg_atmosphere: 4.6,
    avg_food: 4.2,
    avg_hotel: 4.1,
    avg_safety: 4.2,
    avg_rating: 4.4,
    total_reviews: 1876,
    transport_status: 'Active',
    security_score: 4.2,
    year_opened: 2015,
    surface: 'Natural Grass',
    roof_type: 'Open Air',
  },
]